site_name: VastUtils
site_slogon: 便捷安卓开发工具
site_root_url: /
site_domain: vastutils.github.io
site_protocol: https
config_template_dir: config
source: https://github.com/SakurajimaMaii/VastDocs/blob/main
route:
    docs:
        /get_started/zh/: docs/get_started/zh
        /get_started/en/: docs/get_started/en
        /history/zh/: docs/history/zh
        /history/en/: docs/history/en
        /others/zh/: docs/others/zh
        /others/en/: docs/others/en
    pages:
        /: pages/index/zh
    assets:
        /static/: static
        /get_started/assets/: docs/get_started/assets
    blog:
        /blog/: blog
translate:
    docs:
        /get_started/zh/:
        -   url: /get_started/en/
            src: docs/get_started/en
        /history/zh/:
        -   url: /history/en/
            src: docs/history/en
        /others/zh/:
        -   url: /others/en/
            src: docs/others/en
    pages:
        /:
        -   url: /en/
            src: pages/index/en
executable:
    python: python3
    pip: pip3
plugins:
    teedoc-plugin-markdown-parser:
        from: pypi
        config: {}
    teedoc-plugin-theme-default:
        from: pypi
        config:
            dark: true
            env:
                main_color: '#283c86'
    teedoc-plugin-search:
        from: pypi
        config:
            search_hint: Search
    teedoc-plugin-blog:
        from: pypi
        config: {}
    teedoc-plugin-assets:
        from: pypi
        config:
            header_items:
            - /static/css/custom.css
            footer_items:
            - /static/js/custom.js
            env:
                main_color: '#4caf7d'
                second_color: '#0a7d43'
rebuild_changes_delay: 1
robots:
    User-agent: '*'
layout_root_dir: layout
