locale: en
navbar:
    title: VastUtils
    logo:
        alt: my_site logo
        src: /static/image/logo.png
    home_url: /en/
    items:
    -   url: /document/en/
        label: Document
        position: left
    -   url: /history/en/
        label: History
        position: left
    -   url: /others/en/
        label: Other Module
        position: left
    -   url: https://github.com/SakurajimaMaii/VastUtils
        label: github
        target: _blank
        position: right
    -   id: language
        label: 'Language: '
        position: right
        type: language
footer:
    top:
    # -   label: Links
    #     items:
    #     -   label: Build with teedoc
    #         url: https://teedoc.neucrack.com
    #         target: _blank
    #     -   label: Sitemap
    #         url: /sitemap.xml
    -   label: Source code
        items:
        -   label: github
            url: https://github.com/SakurajimaMaii/VastDocs
            target: _blank
        -   label: VastUtils
            url: https://github.com/SakurajimaMaii/VastUtils
            target: _blank
    bottom:
    -   label: '' #'*ICP备********号'
        url: https://beian.miit.gov.cn
        target: _blank
    -   label: '' #'*公网安备***********号'
        url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=****************
        target: _blank
